export const FETCH_BOOKS = 'RESOURCES/BOOKS/FETCH_BOOKS'
export const FETCHING_BOOKS_FAILED = 'RESOURCES/BOOKS/FETCHING_BOOKS_FAILED'
export const IS_FETCHING_BOOKS = 'RESOURCES/BOOKS/IS_FETCHING_BOOKS'
export const SET_BOOKS = 'RESOURCES/BOOKS/SET_BOOKS'
